//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public Nullable<int> id_role_worker { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string patronymic { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual RoleWorker RoleWorker { get; set; }
    }
}
